apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
data:
  config.yaml: |
    branch-protection:
      orgs:
        cb-kubecd:
          repos:
            environment-jstrachan-ad2-staging:
              required_status_checks:
                contexts:
                - promotion-build
        jstrachan:
          repos:
            nodey126:
              required_status_checks:
                contexts:
                - serverless-jenkins
      protect-tested-repos: true
    deck:
      spyglass: {}
    gerrit: {}
    owners_dir_blacklist:
      default: null
      repos: null
    plank: {}
    pod_namespace: jx
    postsubmits:
      cb-kubecd/environment-jstrachan-ad2-staging:
      - agent: tekton
        branches:
        - master
        context: ""
        name: promotion
      jstrachan/nodey126:
      - agent: tekton
        branches:
        - master
        context: ""
        name: release
    presubmits:
      cb-kubecd/environment-jstrachan-ad2-staging:
      - agent: tekton
        always_run: true
        context: promotion-build
        name: promotion-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/nodey126:
      - agent: tekton
        always_run: true
        context: serverless-jenkins
        name: serverless-jenkins
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
    prowjob_namespace: jx
    push_gateway: {}
    sinker: {}
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/nodey126
      - missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jenkins-x/dummy-environment
        - cb-kubecd/environment-jstrachan-ad2-production
      target_url: http://deck.jx.35.189.209.132.nip.io
